### ISSUE TITLE
Iso missing

### ISSUE THREAD

**Issue by DraGiuS** [clayrisser/linux-factory#1]

**Comment by codejamninja** [comment]
I'm so so sorry, I will try and get an iso file soon. I'm finalizing the software that builds the iso. git@github.com:codejamninja/forkbuntu.git

**Comment by codejamninja** [comment]
This project is def not dead though. I'm very excited about it. The goal is to make an OS specifically targeted towards making a software developer more efficient.

**Comment by clayrisser** [comment]
This project has been completely rebuild. Better than ever now. I will have an ISO this month.
